/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kg.pound;

import java.text.DecimalFormat;

/**
 *
 * @author DELL
 */
public class WeightConversion extends javax.swing.JFrame {

    /**
     * Creates new form WeightConversion
     */
    public WeightConversion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Kgtopound = new javax.swing.JLabel();
        gram = new javax.swing.JLabel();
        gramtext = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        poundtext = new javax.swing.JTextField();
        pound = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        kg = new javax.swing.JLabel();
        kgtext = new javax.swing.JTextField();
        tonestext = new javax.swing.JTextField();
        tones = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weight Converter");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));

        Kgtopound.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        Kgtopound.setForeground(new java.awt.Color(255, 255, 255));
        Kgtopound.setText("Gram to kg,tons,pound Converter");

        gram.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        gram.setForeground(new java.awt.Color(255, 255, 255));
        gram.setText("g");

        gramtext.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        gramtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        convert.setBackground(new java.awt.Color(255, 255, 255));
        convert.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        convert.setForeground(new java.awt.Color(255, 0, 0));
        convert.setText("Convert");
        convert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 0, true));
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        poundtext.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        poundtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pound.setBackground(new java.awt.Color(255, 51, 255));
        pound.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        pound.setForeground(new java.awt.Color(255, 255, 255));
        pound.setText("pound");

        clear.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 0, 0));
        clear.setText("clear");
        clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 0, true));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        kg.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        kg.setForeground(new java.awt.Color(255, 255, 255));
        kg.setText("kg");

        kgtext.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        kgtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tonestext.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        tonestext.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tones.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        tones.setForeground(new java.awt.Color(255, 255, 255));
        tones.setText("tons");

        exit.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 0, true));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(gramtext)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kgtext, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(poundtext, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(tonestext, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gram, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tones, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pound, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Kgtopound, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kgtopound, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gram)
                    .addComponent(gramtext, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kg)
                    .addComponent(kgtext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tones)
                    .addComponent(tonestext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poundtext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pound))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       gramtext.setText("");
       poundtext.setText("");
       kgtext.setText("");
       tonestext.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
//        double kilo,pound,result;
//        kilo = Double.parseDouble(kgtext.getText());
//        
//        poundtext.setText(new DecimalFormat("##.##").format(result));
           double g = 0 ,kgresult = 0,poundresult = 0,tonesresult = 0;
           g = Double.parseDouble(gramtext.getText());
           kgresult = (double)g/1000;
           poundresult = (double)(kgresult * 2.2046226218);
           tonesresult = (double)kgresult/1000.0;
           kgtext.setText(new DecimalFormat("##.########").format(kgresult));
           poundtext.setText(new DecimalFormat("##.########").format(poundresult));
           tonestext.setText(new DecimalFormat("##.########").format(tonesresult));
    }//GEN-LAST:event_convertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeightConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeightConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeightConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeightConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeightConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kgtopound;
    private javax.swing.JButton clear;
    private javax.swing.JButton convert;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gram;
    private javax.swing.JTextField gramtext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kg;
    private javax.swing.JTextField kgtext;
    private javax.swing.JLabel pound;
    private javax.swing.JTextField poundtext;
    private javax.swing.JLabel tones;
    private javax.swing.JTextField tonestext;
    // End of variables declaration//GEN-END:variables
}
